FROM ruby:2-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN apk add --no-cache \
      nodejs \
      postgresql-dev \
      tzdata

COPY Gemfile /usr/src/app/
COPY Gemfile.lock /usr/src/app/

RUN apk add --no-cache --virtual .build-deps \
      build-base \
    && bundle install \
    && apk del .build-deps

COPY . /usr/src/app

RUN RAILS_ENV=production bundle exec rails assets:precompile

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
